//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlementLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiteratureReference
    {
        public int Id { get; set; }
        public Nullable<int> Literature { get; set; }
        public Nullable<int> Settlement { get; set; }
        public string Pages { get; set; }
        public string TempToken { get; set; }
    }
}
