//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettlementLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SettlementDB : DbContext
    {
        public SettlementDB()
            : base("name=SettlementDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<LiteratureReference> LiteratureReferences { get; set; }
        public virtual DbSet<Literature> Literatures { get; set; }
        public virtual DbSet<TimeperiodRelative> TimeperiodRelatives { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }
    }
}
